# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dr.rer.nat. Ilwook Kim
title: Computational Biologist
email: ilwook.kim.1982@gmail.com
website: ilwookkim.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  ilwookkim
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: ilwook-kim-0682ab89
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Computational biologist with 3+ years' experience researching <mark>next-generation sequencing (NGS)</mark> and <mark>cancer genomics</mark> and postdoctoral researcher with +10 years' experience in molecular biology. Well-versed in programming languages including <mark>R</mark> for NGS analysis. Experience in both Computational biology and wet-lab experiments.


content:
  - title: Work Authorization # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Authorized to work in the EU for any employer
        quote: >
          EU Familienangehöriger ART 10 RL 2004/38/EG
          

  - title: Work History # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FLI
        quote: >
          Leibniz Institute on Aging – Fritz Lipmann Institute
        additional_links:
          - title:  FLI
            icon: fab fa-globe
            url: http://www.fli-leibniz.de/
        sub_title: Guest Scientist
        caption: Jan 2021 - Present
        description: | # this will include new lines to allow paragraphs
            * Aging research using 3D mouse organoid model

      - layout: left
        title: Biotec
        quote: >
          Biotechnology Center of the TU Dresden
        additional_links:
          - title:  Biotec
            icon: fab fa-globe
            url: https://tu-dresden.de/cmcb/biotec
        sub_title: Post-doctoral Bioinformatician
        caption: Oct 2019 - Dec 2020
        description: | # this will include new lines to allow paragraphs
            * Genome/Transcriptome-wide association study
            * Next-generation sequencing (NGS) analysis
            * Gene co-expression network analysis

      - layout: left
        title: University Hospital Carl Gustav Carus Dresden
        quote: >
          Department of Visceral, Thoracic and Vascular Surgery
        additional_links:
          - title:  UKDD
            icon: fab fa-globe
            url: https://www.uniklinikum-dresden.de/de/das-klinikum/kliniken-polikliniken-institute/vtg/forschung/Forschungslabor/ag-stange
        sub_title: Post-doctoral Scientist
        caption: Nov 2017 - Mar 2019
        description: | # this will include new lines to allow paragraphs
            * Personalized treatment of gastric cancer
            * Circulating tumor cells research
            * 3D gastric cancer organoid line generation

      - layout: left
        title: Geneclone co.
        quote: >
          Biotechnology of Microbial Enzymes and Antibodies
        sub_title: Research Associate
        caption: Feb 2009 - Aug 2009
        description: | # this will include new lines to allow paragraphs
            * Taq-DNA polymerase production
            * Antibody production


  - title: Education 
    layout: list 
    content:
      - layout: left
        title: Friedrich Schiller University Jena / Ulm University
        caption: Jan 2014 - Nov 2017 / Jan 2011 - Dec 2013
        sub_title: Doktor der Naturwissenschaften (Dr. rer. nat)
        quote: >
          Leibniz Institute on Aging – Fritz Lipmann Institute
          Max-Planck-Research Group on Stem Cell Aging
        description: | # this will include new lines to allow paragraphs
          * Thema : Sirt1 deletion improves intestinal atrophy in telomere dysfunctional mice by impairing induction of DNA damage responses.
          * Hematopoietic stem cells quiescence
          * HIV progression in aging

      - layout: left
        title: Kyonggi University, Korea
        caption: Feb 2007 - Feb 2009
        sub_title: Master of Science (M.Sc)
        quote: >
          Department of Biology
        description: | # this will include new lines to allow paragraphs
          * Thema : Rapid detection of virulence stx2 gene of Enterohemorrhagic Escherichia coli using two-step ultra-rapid real-time PCR.
          * Rapid detection of diseases of A. mellifera.

      - layout: left
        title: CQ Beratung+Bildung GmbH, Berlin
        caption: May 2019 - Dec 2019
        sub_title: Further education
        quote: >
          Weiterbildung für Biologen & Informatiker
        description: | # this will include new lines to allow paragraphs
          * Programmierung (Linux,C++) Python
          * Bioinformatik und Biodatenbanken
          * Next Generation Sequencing-Datenauswertung
          * Anwendungsbezogene Biostatistik (R)



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
